name = "QuantumNLDiffEq"
uuid = "5411918f-e61c-4722-a33e-8517a813f4bd"
authors = ["SciML"]
version = "0.0.1"

[deps]

[compat]
julia = "1.6"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SafeTestsets", "Test"]
